server:
  shutdown: graceful

spring:
    application:
        name: gerenciamento-perfis-github-api
    datasource:
        url: jdbc:postgresql://localhost:5432/desafio_github
        username: desafio_github
        password: 12345
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
            dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    flyway:
            enabled: true
            locations: classpath:db/migration
github:
    api:
        users: https://api.github.com/users?per_page=30
jwt:
    secret: minha_chave_super_secreta_para_token_123456
    expiration: 3600000
